# Generated by Django 2.1.3 on 2019-07-14 15:16

import Apps.encuestador.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50)),
                ('password_hashed', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profileType', models.IntegerField(choices=[(Apps.encuestador.models.ProfileEnum(1), 1), (Apps.encuestador.models.ProfileEnum(2), 2), (Apps.encuestador.models.ProfileEnum(3), 3), (Apps.encuestador.models.ProfileEnum(4), 4)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=50)),
                ('client_logo', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('contact', models.CharField(max_length=50)),
                ('client_company_name', models.CharField(max_length=100)),
                ('constitution_year', models.IntegerField()),
                ('number_employees', models.IntegerField()),
                ('is_corporate_group', models.BooleanField()),
                ('is_family_company', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_contact_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Config_surveys_by_clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_surveys', models.IntegerField(blank=True, default=None, null=True)),
                ('used_surveys', models.IntegerField(default=0)),
                ('survey_conf_desc', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Customized_instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_general_description', models.TextField(blank=True, default=None, null=True)),
                ('custom_feature_description', models.TextField(blank=True, default=None, null=True)),
                ('custom_disclaimer', models.TextField(blank=True, default=None, null=True)),
                ('custom_user_instructions', models.TextField(blank=True, default=None, null=True)),
                ('custom_contact_info', models.TextField(blank=True, default=None, null=True)),
                ('custom_thanks', models.TextField(blank=True, default=None, null=True)),
                ('access_code', models.CharField(default=None, max_length=50)),
                ('prefix', models.CharField(default=None, max_length=6)),
                ('config_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Config_surveys_by_clients')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument_structure_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_minor_version', models.CharField(max_length=20)),
                ('change_reason', models.TextField()),
                ('is_active', models.BooleanField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('instrument_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsByInstrument', to='encuestador.Instrument_header')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_classification_structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField(choices=[(Apps.encuestador.models.ClassificationChoice(1), 1), (Apps.encuestador.models.ClassificationChoice(2), 2), (Apps.encuestador.models.ClassificationChoice(3), 3)])),
                ('i18n_code', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Items_respon_by_participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_numeric', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Parametric_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant_response_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=None)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('is_directive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Response_format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[(Apps.encuestador.models.ResponseFormatType('Yes/No'), 'Yes/No'), (Apps.encuestador.models.ResponseFormatType('Likert 9 points'), 'Likert 9 points'), (Apps.encuestador.models.ResponseFormatType('Likert 6 points'), 'Likert 6 points')], max_length=15)),
                ('parametric_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Parametric_master')),
            ],
        ),
        migrations.CreateModel(
            name='Surveys_by_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acces_code', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('config_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Config_surveys_by_clients')),
            ],
        ),
        migrations.CreateModel(
            name='Trans_instrument_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_description', models.TextField(blank=True, default=None, null=True)),
                ('feature_description', models.TextField(blank=True, default=None, null=True)),
                ('disclaimer', models.TextField(blank=True, default=None, null=True)),
                ('user_instructions', models.TextField(blank=True, default=None, null=True)),
                ('contact_info', models.TextField(blank=True, default=None, null=True)),
                ('thanks', models.TextField(blank=True, default=None, null=True)),
                ('i18n_code', models.CharField(max_length=2)),
                ('instrument_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='encuestador.Instrument_header')),
            ],
        ),
        migrations.CreateModel(
            name='Trans_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('i18n_code', models.CharField(max_length=40)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='encuestador.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Trans_parametric_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(max_length=50)),
                ('i18n_code', models.CharField(max_length=2)),
                ('numeric_value', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('parametric_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailsParameters', to='encuestador.Parametric_master')),
            ],
        ),
        migrations.AddField(
            model_name='participant_response_header',
            name='area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area', to='encuestador.Trans_parametric_table'),
        ),
        migrations.AddField(
            model_name='participant_response_header',
            name='customized_instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Customized_instrument'),
        ),
        migrations.AddField(
            model_name='items_respon_by_participants',
            name='participant_response_header',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsesList', to='encuestador.Participant_response_header'),
        ),
        migrations.AddField(
            model_name='item_classification_structure',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='itemsClass_Category', to='encuestador.ItemClassification'),
        ),
        migrations.AddField(
            model_name='item_classification_structure',
            name='component',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsClass_Component', to='encuestador.ItemClassification'),
        ),
        migrations.AddField(
            model_name='item_classification_structure',
            name='dimension',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='itemsClass_Dimension', to='encuestador.ItemClassification'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='itemsByCategory', to='encuestador.ItemClassification'),
        ),
        migrations.AddField(
            model_name='item',
            name='component',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsByComponent', to='encuestador.ItemClassification'),
        ),
        migrations.AddField(
            model_name='item',
            name='dimension',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='itemsByDimension', to='encuestador.ItemClassification'),
        ),
        migrations.AddField(
            model_name='item',
            name='response_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Response_format'),
        ),
        migrations.AddField(
            model_name='instrument_structure_history',
            name='new_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_newItem', to='encuestador.Item'),
        ),
        migrations.AddField(
            model_name='instrument_structure_history',
            name='original_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_originalItem', to='encuestador.Item'),
        ),
        migrations.AddField(
            model_name='instrument_structure_history',
            name='previous_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_previousItem', to='encuestador.Item'),
        ),
        migrations.AddField(
            model_name='config_surveys_by_clients',
            name='instrument_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Instrument_header'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestador.Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuestador.Client'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuestador.Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
