# Generated by Django 2.0.4 on 2018-10-28 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encuestador', '0002_dataSeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveys_by_client',
            name='client',
        ),
        migrations.RemoveField(
            model_name='surveys_by_client',
            name='company',
        ),
        migrations.AddField(
            model_name='config_surveys_by_clients',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config_surveys_by_clients',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customized_instrument',
            name='acces_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
