# Generated by Django 2.0.4 on 2018-10-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestador', '0003_auto_20181027_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customized_instrument',
            name='client',
        ),
    ]
