# Generated by Django 2.0.4 on 2018-10-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestador', '0004_remove_customized_instrument_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customized_instrument',
            name='num_completed_responses',
        ),
        migrations.RemoveField(
            model_name='customized_instrument',
            name='num_partial_responses',
        ),
        migrations.AlterField(
            model_name='customized_instrument',
            name='acces_code',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
