# Generated by Django 2.0.4 on 2018-10-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestador', '0005_auto_20181028_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customized_instrument',
            old_name='acces_code',
            new_name='access_code',
        ),
    ]
