# Generated by Django 2.0.4 on 2018-10-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestador', '0006_auto_20181028_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='customized_instrument',
            name='prefix',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
